---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - apt-transport-https
    state: present

- name: Install k3s agent
  shell: >
    curl -sfL https://get.k3s.io | 
    K3S_URL=https://{{ hostvars[groups['control_plane'][0]]['control_plane_ip'] }}:6443
    K3S_TOKEN={{ hostvars[groups['control_plane'][0]]['k3s_token'] }}
    sh -
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start k3s agent
  systemd:
    name: k3s-agent
    enabled: yes
    state: started
x
